from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "85WId1Oohv3lUleICAyycwGH"

# Create the client instance
client = Elasticsearch(
    cloud_id="LearningElastic:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyRhYjczNmYzMTcxYmM0NjA5OTViM2QwNGRjN2M0OGEyNyQ0ZmNlZWY0NWE3Mjc0M2U4ODM1ZWZiMjJiMThlYjk2OQ==",
    ca_certs="ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD),
    # api_key="NFVuV2tJZ0JGekJxaHhUWnIxTUM6ekFSMkJtVDVTaXFsTllJQ0p6SFZiUQ=="
)

# Successful response!
print(client.info())

data_1 = {"city": "Cosenza", "country": "Italy"}
data_2 = {"city": "Rende", "country": "Italy"}
data_3 = {"city": "Praga", "country": "Belgium"}
data_4 = {"name": "Mario"}
new_data = {"name": "Prova"}

client.index(index="cities", id="1", document=data_1)
client.index(index="cities", id="2", document=data_2)
client.index(index="cities", id="3", document=data_3)
client.index(index="prova", id="1", document=data_4)
client.update(index="prova", id="1", doc=new_data)
res = client.get(index="cities", id="1")
print(res)
